### PR TITLE
.Net Standard 2.0

### LINKED ISSUE #15: .NET Standard support
In case someone comes here looking to see if this library can support .NET Standard and .NET Core, I've attached the compatibility report from apiport.exe. No support possible until .NET Standard 2.0 it seems.

[ApiPortAnalysis.xlsx](https://github.com/jbevain/mono.reflection/files/551838/ApiPortAnalysis.xlsx)

@hazzik in case you look at this for DelegateDecompiler

### PR DESCRIPTION
**Pull request by hazzik**
Closes #15

### CODE REVIEW

**Comment by jbogard** [comment]
Looks like with netstandard2.0 it's fully compatible!

**Comment by hazzik** [comment]
@jbogard how's Sydney? 

I'll update the PR with the RTM version shortly.

**Comment by hazzik** [comment]
Done

**Comment by jbogard** [comment]
@jbevain lgtm!

**Comment by raunakpandya** [comment]
Was this support added?

**Comment by hazzik** [comment]
>Was this support added?

No :(

**Comment by pgarbo** [comment]
> @jbevain Can we get this merged please?

as above

**Comment by jbevain** [comment]
Thanks, I've pushed support for .NET SDK style projects and .NET Standard 2.0.

**Pull request closed without merging**
