### PR TITLE
Add optional instruction to getter pattern to match the IL generated …

### PR DESCRIPTION
**Pull request by NickStrupat**
…by auto-properties in C#, VB.NET and F#.

### CODE REVIEW

**Comment by jbevain** [comment]
Hey, thanks! That's branching on the ret?

**Comment by NickStrupat** [comment]
Yes. VB.NET emits an unconditional branch to the next line (ret).
:)






On Fri, Jan 15, 2016 at 3:54 PM -0800, "Jb Evain" <notifications@github.com> wrote:












Hey, thanks! That's branching on the ret?

**Comment by jbevain** [comment]
Thanks!

**Comment by NickStrupat** [comment]
Could I bug you to update the NuGet package? :smile:

**Comment by jbevain** [comment]
I pushed a new one!

**Comment by NickStrupat** [comment]
Hoorah!

**Pull request merged**
